# Generated by Django 3.0.8 on 2020-07-10 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('timecreated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 10, 17, 58, 18, 295444))),
            ],
        ),
    ]
