# Generated by Django 3.0.8 on 2020-07-10 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200710_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='timecreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 10, 19, 55, 54, 274884)),
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='timecreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 10, 19, 55, 54, 202836)),
        ),
    ]
